### ISSUE TITLE
Create widgets via registry

### ISSUE THREAD

**Issue by kitsonk** [dojo/app#22]
(Original issue description was rewritten by @novemberborn)

dojo/widgets#23 describes a use case where parent widgets need to create their children. The children won't have been pre-registered with the app factory. It should be possible for the parent widget to use the app factory's registry to create the children.

The interface proposed in https://github.com/dojo/widgets/pull/24 adds a `create(parent, factory, options)` method to the (widget) registry. What's clear here is that the parent provides the factory and initial options. The factory doesn't have to be registered with the app.

Control is inverted from the parent to the registry. The registry can then generate a unique ID (string), add the `stateFrom` option (without overriding an existing option) pointing at any default store, create the instance, add it to the registry, and then return it. This should return a promise, of course.

**Comment by novemberborn** [comment]
I've done an implementation of this in <https://github.com/dojo/app/pull/26>. Notably the `create()` method here does not take a parent. Instead the calling code should append created widgets. This is useful because `widget.children` can be a list or a map: the app factory shouldn't have to worry about the difference.
