### ISSUE TITLE
Feature - "Binding" for Applications

### ISSUE THREAD

**Issue by kitsonk** [dojo/app#24]
# User Story

A developer may need to describe a part of the application that is bound to another set of data, where there is a mapping of data to widget instances, where the initial state of the widget is determined by one of the items of a data set.

For example, if we have a list of "todo" items, we would want to instantiate an instance for each item in that list, as well as observe changes to that list so if items get added or deleted, the associate widget and state gets added or deleted.

# Considerations

- Do we need to get further with our query/transform APIs to be able to make this work?
- Conceptually we would need to express:
  - The class of widget to instantiate
  - How the options for the factory are derived from the source data
  - Potentially actions to fire on different mutations of the source data (e.g. add, delete, put, patch)
  - How to connect the widgets to actions and stores
- @matt-gadd pointed out that our "application descriptor" model is similar to Wire.js and that their [ToDoMVC implementation](https://github.com/SenchaProSvcs/todomvc/blob/801e75b4d81223a39e69f29a0b4ccf8c1ee6b5ae/labs/architecture-examples/cujo/app/main.js#L34) expresses a very similar feature to what we are discussing here.

My feeling is this needs a decent amount of thought and design before we could begin to implement, but the use case will be rather common.

**Comment by kitsonk** [comment]
I was just thinking about this.  Is `dojo/app` the right place to put this?  Would it not be better to have a "bound" widget that used the `registry.create()` (see: dojo/widgets#24) based on a set of observed data?

**Comment by novemberborn** [comment]
> I was just thinking about this. Is dojo/app the right place to put this?

I do struggle to see how this would fit in to the application factory, but maybe that's because I'm not familiar enough with Wire.js.

> Would it not be better to have a "bound" widget that used the registry.create() based on a set of observed data?

That seems sensible. You can still configure that widget in the loaded definition, it's just that the config sits at a different nesting level.

My only concern would be that the application factory doesn't really expose widget factories. `registerWidgetFactory` registers a factory for a single widget instance. `registerCustomElementFactory` registers a factory that can create multiple instances but those factories cannot be referenced other than via DOM elements.

If the factories are referenceable then widgets can call `create()` with an identifier string. For your "bound" widget suggestion it would make the widget fully customizable. It would give us a nice pattern for extending the application factory.

**Comment by novemberborn** [comment]
@kitsonk?

**Comment by kitsonk** [comment]
We already have a reference for a factory, it is called the MID, which can be absolute or relative.  There can be a shortcut to that which I am going to be proposing for `dojo/app`, but I think it is hard to externalise that inside a widget, because it would require the downstream developer to make sure they registered the module as the right ID used by the widget designer.

Anyways, I would like to get some more thoughts from @matt-gadd and I think there is a lot of what is covered in #33 that will impact this.  In fact, this issue might get folded into that.

**Comment by novemberborn** [comment]
@kitsonk @matt-gadd now that #33 has been resolved, and given #55, is there any further work required for this issue?

**Comment by kitsonk** [comment]
Personally, I think we generally have agreed that this sort of "binding" and enumeration of data should be handled by `dojo/data` (or `stores` if we put it there), but I would like to get input from @matt-gadd @agubler since this really came out the challenges of TodoMVC.

**Comment by kitsonk** [comment]
Instead of baking this functionality directly into `app` we should instead look to integrate `dojo-data` into `app` like we have other architectural components, and have `dojo-data` perform this architectural function.
