### ISSUE TITLE
Incremental Declarative

### ISSUE THREAD

**Issue by kitsonk** [dojo/app#84]
The ability to have the `app` retrieve HTML or POJO DSL and "attach" it to the current page.

**Comment by novemberborn** [comment]
I think the starting point should be loading a POJO definition after the app has started, and similarly realizing a new `Element` (possibly detached from the current document). Quite how it loads the definitions / elements we can resolve later.

I suppose we'd want to render any new widgets [with roots](https://github.com/dojo/app/issues/30#issuecomment-255110703). Repeatedly calling `start()` seems odd so we'd need some other method to trigger that. We may also want to provide a different root element. Will try and flush this out further in a prototype.

**Comment by novemberborn** [comment]
`loadDefinition()` can already load a new POJO definition, even after the app has started. The same goes for `realize()`. Really the problem is attaching new widgets.

I don't see how we'd do that without first inventing "scene management". There is no way of declaring that a previously rendered widget is no longer wanted, so parsing additional markup or loading new definitions can only be additive. Yes, we could try and render new rooted widgets but without destroying old widgets that can only serve a very narrow use case.

I'm not sure we understand enough about scene management requirements yet to move forward with that, perhaps as the Monster Cards example progresses.

**Comment by kitsonk** [comment]
We would address that in any sort of declarative DSL we might eventually support.
