### ISSUE TITLE
`createCustomWidget` is not preserving the `state`

### ISSUE THREAD

**Issue by lzhoucs** [dojo/app#92]
In `dojo/app` `2.0.0-alpha.9`, `state` is lost when [calling `customFactory`](https://github.com/dojo/app/commit/4ff7f72ca92d04ebbba627a953337d0d0931f0c7#diff-3e8e21b91471e48a7df3e3deb6791992R584). This causes issues in custom widget factories where `state` is expected.

For example, Monster Card app is locking down to previous version [2.0.0-alpha.8](https://github.com/dojo/examples/blob/master/monster-cards/package.json#L21) of `dojo/app` , because it is [expecting `state` in the `options`](https://github.com/dojo/examples/blob/master/monster-cards/src/widgets/card/createCardSummary.ts#L26)

**Comment by agubler** [comment]
Hey @izhoucs, this is actually working as expected. I did propose a change to support `state` in `options` but it was agreed that previously it was a side affect rather than intentional. 

Once the proposal for `d` in widgets has been completed then we will be able to refactor these widgets to not require the state from options.

**Comment by agubler** [comment]
My previous proposal was #93

**Comment by lzhoucs** [comment]
Oh, sorry I did't know the background of this. #93 seems to be my PR for this.

The reason I am trying to address it now, is because @maier49 and I have been working on integrating new `dojo/stores` into the two example apps. We have made stores related changes in `dojo/app` based on the latest version, however monster app currently doesn't work with the latest `dojo/app` for the reason mentioned above.

**Comment by agubler** [comment]
(I updated the reference to #87)

I thought that may have been the reason for the change, I'm not actually against this change (as you can tell i proposed something similar myself!)

Perhaps we should restore the side affect of options containing state for dynamically created widgets in order to help transition to the new stores? Depending on how long it'all take to get `d` into widgets, released and Monster refactored?

Thoughts @kitsonk

**Comment by kitsonk** [comment]
I sort of hate unwinding things that need to be fixed.  I would hate for us to end up with more code that sort of accidentally depends upon a behaviour that doesn't work, though I can understand the need to be able to make forward progress.

So I guess we can restore it, but we need a clear a clear issue, as a beta blocker, to take it out again.

**Comment by agubler** [comment]
@kitsonk given conversations with Mark previously, I'm inclined to agree that I'd rather not add something so that consumers can still use the side affect... Perhaps we should aim for getting `d` reviewed, merged and released? Then I think this should become a non issue.

**Comment by dylans** [comment]
@agubler Is this still needed now that `d`, `v` and `w` have landed?

**Comment by matt-gadd** [comment]
as @dylans said, this is no longer relevant.
